### ISSUE TITLE
GatewayResourceConfig missing?

### ISSUE THREAD

**Issue by davidmco65** [bbilger/jrestless#16]
Im trying to use 0.4.0 but can't locate GatewayResourceConfig class.  What jar is it contained within?

**Comment by bbilger** [comment]
Oh sorry. Just released 0.4.0 yesterday and the example is not up-to-date.
Just use ResourceConfig and register GatewayFeature. (new ResourceConfig().register(GatewayFeature.class)).
Will fix ASAP, sorry

**Comment by bbilger** [comment]
@davidmco65 I updated the usage example accordingly (tested with serverless v1.2.1). Let me know if you run into any more issues.

FYI: I will update all [examples](https://github.com/bbilger/jrestless-examples) (and add more) for version 0.4.0 by the end of the week.

**Comment by bbilger** [comment]
all examples have been updated: https://github.com/bbilger/jrestless-examples

**Comment by davidmco65** [comment]
Thank you, it's working better now.  Having another issue, but I'll post separately about that.
