### ISSUE TITLE
Question : Best route for Guice based DI

### ISSUE THREAD

**Issue by remonvv** [bbilger/jrestless#22]
Hi,

Wondering how one can go about enabling Guice based dependency injection? So the rough equivalent to https://jersey.java.net/nonav/apidocs/1.8/contribs/jersey-guice/com/sun/jersey/guice/spi/container/servlet/GuiceContainer.html

**Comment by bbilger** [comment]
Hi @remonvv ,
I set up an example for Guice: https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-guice

I used the guice-bridge as described here: http://stackoverflow.com/a/35086248

Hope this helps!

Let me know if this works for you and/or if you have any questions.

**Comment by remonvv** [comment]
Hi @bbilger 

Great! That should be a good starting point for further experimentation. Appreciate the effort!
