### ISSUE TITLE
Problem serializing Response when deployed to AWS Lambda

### ISSUE THREAD

**Issue by davidmco65** [bbilger/jrestless#26]
Hi, I'm having an issue when I've deployed my Lambda to AWS and hooked it up to API Gateway.

I use the API Gateway Test functionality to test the Lambda.  It makes the call, the code executes, but when I do the Response.ok()... I get the following messages in my CloudWatch log:

`org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo`
`SEVERE: MessageBodyWriter not found for media type=application/json, type=class com...`

From what I've read, there's a problem with the glassfish jersey media implementation.  So I'd like to just switch over to Jackson's implementation.  Is this something you've run into or done in the past?

Thanks,
David

**Comment by bbilger** [comment]
Hi @davidmco65 
1. Do you have a dependency to `org.glassfish.jersey.media:jersey-media-json-jackson:2.23`?
2. Is your DTO a JAXB class (`@XmlRootElement`)? If so, are you sure you have a no-args constructor?
3. If you invoke the function through APIGateway - for example using curl - does it work?

If 1. and 2. does not apply in your case: can you send me some code + dependencies, please.

**Comment by bbilger** [comment]
Also:
I quickly deployed https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-usage-example, tested it through APIGW's test functionality and can't see any issues...

![apigw_test](https://cloud.githubusercontent.com/assets/6827090/22124985/3f6c844e-de92-11e6-9652-bfe4a960fadb.png)

**Comment by davidmco65** [comment]
Here are my dependencies in my pom.xml file:
`		<dependency>
			<groupId>com.jrestless.aws</groupId>
			<artifactId>jrestless-aws-gateway-handler</artifactId>
			<version>0.4.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.glassfish.jersey.containers</groupId>
					<artifactId>project</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-server</artifactId>
			<version>2.23</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
			<version>2.23</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.2.5.Final</version>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.40</version>
		</dependency>
		<dependency>
			<groupId>com.github.v-ladynev</groupId>
			<artifactId>fluent-hibernate-core</artifactId>
			<version>0.3.1</version>
		</dependency>
`

My DTO is a Pojo:
`public class ContactObject implements Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4663016387257579780L;
	private ContactObject.Contact contact;
	private ContactObject.Address address;
	private String contactType;
	
	/**
	 * 
	 */
	public ContactObject()
	{
	}

	...
`

Do I really need the @XmlRootElement if I'm really only interested in Json response body?

I can test through API GW Test function, but can't through cURL.. just get "Missing Authentication Header" error.

Thanks for your help!
David

**Comment by bbilger** [comment]
Maven, I see. I remember having some issues with maven and jrestless or rather jersey in an uber-jar...

Are you configuring the maven shade plugin as follows:
```
<configuration>
   <createDependencyReducedPom>false</createDependencyReducedPom>
  <!-- http://stackoverflow.com/questions/29107376/jersey-problems-with-maven-shade-plugin -->
  <transformers>
    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
    </transformers>
</configuration>
```
See https://github.com/bbilger/jrestless-examples/blob/master/pom.xml#L48

**Comment by bbilger** [comment]
Sorry @davidmco65, I was short on time today.
http://stackoverflow.com/questions/29107376/jersey-problems-with-maven-shade-plugin looks exactly like your issue => try to configure maven-shade as suggested above.
You also don't need to exclude  `org.glassfish.jersey.containers` in jersestless 0.4.0, anymore (see #14)
You also don't need to use "@XmlRootElement" if you don't need XML (using it has the advantage that you can return both JSON and XML)
If you cannot access it via curl, then you probably didn't set up APIGW properly.

Let me know if it works.

**Comment by davidmco65** [comment]
Hi Bjorn,

Thank you for your help!  Your previous message about the configuration 
of the Maven Shade plugin did the trick! Thanks so much for your 
valuable library and all of the time you've obviously put into it.  It 
will be the basis of all of our services going forward.

Regards,

David

**Comment by bbilger** [comment]
I am happy to help!
Good to hear it's used and valuable.
