### ISSUE TITLE
Question - Run dropwizard applications with jrestless on aws lambda

### ISSUE THREAD

**Issue by vikrampatankar** [bbilger/jrestless#27]
I was looking to have some existing dropwizard applications run on aws lambda with minimal changes to them. Could I use jrestless for that ? Dropwizard uses Jersey & Jetty internally.

**Comment by bbilger** [comment]
Hi @vikrampatankar ,
Good question. I actually never used Dropwizard but as far as I know it's tightly coupled with Jetty. So there's probably no easy way to remove the the embedded Jetty that comes with Dropwizard - though it shouldn't be impossible: I saw some posts/projects where people managed to deploy Dropwizard in a Servlet container (JRestless, however, is not a Servlet-compliant container). 
Even if you manage manage to let Dropwizard use JRestless as a JAX-RS container, I am not sure what other magic Dropwizard does and if it will work.
