### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by klebermagno** [bbilger/jrestless#30]
Jrestless look be a interesthing project and is very use full for me. 
I I would like to contribute with jrestless.

Exist a roadmap ?
What is your pretension for the future of the project ?

**Comment by bbilger** [comment]
Hi @klebermagno ,
I am happy to hear this.

No, I don't have a real roadmap. I extend JRestless once API Gateway offers new features (binary support, etc.), bugs are opened or features are requested. At the moment I am trying to work on the remaining open issues and to document the framework. 

I would love to see JRestless growing but at the moment I am the only developer and work on it in my spare time, only.

I hope this answers your questions - if not, let me know.

**Comment by bbilger** [comment]
just in case this wasn't clear: I would highly appreciate contributions ;)

**Comment by bbilger** [comment]
closing since inactive... feel free to re-open
