### ISSUE TITLE
Weld integration

### ISSUE THREAD

**Issue by marciodel** [bbilger/jrestless#32]
In order to Weld work with Jrestless I needed to change the packages to include META-INF/beans.xml.

Is it possible to include those files in next release?

Thanks!

**Comment by bbilger** [comment]
Hi @marciodel ,
Can you provide some minimal example, then I'll check.

Thanks!

**Comment by marciodel** [comment]
Hi @bbilger, 

   I have included in my project dependencies "org.jboss.weld.se:weld-se-core:2.4.2.SP1" and "org.glassfish.jersey.ext.cdi:jersey-weld2-se:2.25.1". 

  In the request handler I have added Weld initialization. 

```
		Weld weld = new Weld();
		weld.initialize();
		
               config = new JAXRSApplication().register(GatewayFeature.class);

		init(config); 
		start();
```

    Adding META-INF/beans.xml in each .jar made it work. I've dowloaded the project and made the changes to include it.

   I'm not a CDI expert, just a regular user. :) But what I've understood is that Weld (I don´t know about other CDI implementation) scans the .jar implementations that contains the META-INF/beans.xml. 

Best regards

**Comment by bbilger** [comment]
Hi @marciodel ,
Thanks!
I am a little busy at the moment but I will try to take a look as soon as possible.

**Comment by marciodel** [comment]
Just a remark. I am deploying to AWS lambda a zip file containing a lib folder with the dependencies inside it.

**Comment by marciodel** [comment]
Thanks! 

Take your time. I have managed to make my project to work with those changes. 

Congratulations for this great project!

**Comment by bbilger** [comment]
I think I found the issue: the filters injected the request using @Inject which does not seem to work when using CDI/Weld (http://stackoverflow.com/questions/13419887/injection-of-httpservletrequest/13420108#13420108). So I switched to inject it using @Context.
As far as I can see so far we do not need to have a beans.xml in every module.

(I hope to be finally able to release JRestless 0.5.0 at the end of this week or at the beginning of next week; I will provide an example for CDI afterwards - will leave the bug open until then)

**Comment by bbilger** [comment]
Hi @marciodel ,
I just released 0.5.0 including this fix and added a CDI/Weld example: https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-cdi

Hope this solves your problem!

**Comment by bbilger** [comment]
assuming fixed - if not, then please re-open

**Comment by marciodel** [comment]
Hi bbilger, sorry for the delayed answer. I was on vacation. I'll test it and provide a feedback as soon as possible. Thanks!

**Comment by marciodel** [comment]
I've tested with the version 0.5.1 and it is working flawlessly.

Thanks!

**Comment by bbilger** [comment]
Hi @marciodel ,
thanks for the feedback.
