### ISSUE TITLE
onRequestFailure is never called

### ISSUE THREAD

**Issue by lewisdaly** [bbilger/jrestless#33]
I've found that even when a request fails (eg. an exception is thrown in my handler), the `onRequestSuccess` hook is called with a status code of 500.

Is this what is meant to happen? What is the preferred method for dealing with exceptions? My desired approach would be to catch any exception in `onRequestFailure` and return an appropriate response.

I've noticed that in line 357 of JRestlessHandlerContainer.java, `commit()` is called. If I throw a `RuntimeException` here instead, my `onRequestFailure` hook is triggered and I can go on my merry way.

Hope this makes sense, and you can help!

**Comment by bbilger** [comment]
Hi @lewisdaly,
Sorry for the late response.
I must admit that this is a little confusing but onRequestFailure is invoked only if the container fails.
Application exceptions should be handled using JAX-RS' exception mappers mechanism and be registered on the ResourceConfig.
https://jersey.java.net/documentation/latest/representations.html#d0e6754

```java
ResourceConfig config = new ResourceConfig();
config.register(SomeAppExceptionMapper.class);
config.register(GlobalExceptionMapper.class);
...
@Provider
public static class SomeAppExceptionMapper implements ExceptionMapper<SomeAppException> {
  @Override
  public Response toResponse(SomeAppException exception) {
    return Response.status(Status.INTERNAL_SERVER_ERROR).entity(...).build();
  }
}
@Provider
public static class GlobalExceptionMapper implements ExceptionMapper<Exception> {
  @Override
  public Response toResponse(Exception exception) {
    return Response.status(Status.INTERNAL_SERVER_ERROR).entity(...).build();
  }
}
```

I hope this helps.

**Comment by lewisdaly** [comment]
Thanks! It works a charm. I had tried some stuff with JAX-RS exceptions, but I never figured out that I needed to register them.

Perhaps I can add an example showing how this works.

**Comment by bbilger** [comment]
Hi @lewisdaly ,
I think you do not necessarily have to register them but if you don't do so, you need to have the "@Provider" annotation in place and let JAX-RS/Jersey know where it should search for (ResourceConfig#packages).
I extended the showcase example to show how it works: [aws-gateway-showcase](https://github.com/bbilger/jrestless-examples/tree/master/aws/gateway/aws-gateway-showcase) ( [Commit](https://github.com/bbilger/jrestless-examples/commit/7367277ce36dce3473e8f8abc788e23f9e04015e) )

Thanks for your feedback!
