### ISSUE TITLE
CHANGELOG not updated for 0.5.0

### ISSUE THREAD

**Issue by injeniero** [bbilger/jrestless#34]
Hi bbliger,

It seems you forgot to update the changelog to include 0.5.0 release.

Thanks for the great work!!

PS: I was able to integrate dropwizard 1.0.6 with your project and deploy to AWS Lambda :-)

**Comment by bbilger** [comment]
Hi @injeniero,
Indeed, I forgot to update the changelog, thanks...time for a release plan ;)

Impressive: I did not expect it were possible to integrate dropwizard with JRestless. Another user had exactly this question (#27). Is there some code you can share, or explain how you integrated it?

Thanks!

**Comment by injeniero** [comment]
Thanks for the hard work. I will share on #27.
