### ISSUE TITLE
clarify logging support

### ISSUE THREAD

**Issue by ags799** [bbilger/jrestless#37]
Firstly, thanks for authoring this project! It's greatly helped me get up to speed with Serverless!

I'm having some trouble with logging. I've tried following [your example](https://github.com/bbilger/jrestless-examples/blob/4f273384cecad3534d6939e58b71984b3c4e9efd/aws/service/aws-service-usage-example-client/src/main/java/com/jrestless/aws/examples/RequestHandler.java#L29). However, after deploying such code and `curl`ing an endpoint, `serverless logs -f $function_name` doesn't indicate any logging is being done.

[Here's my handler](https://github.com/ags799/learn-java/blob/as/dynamodb/src/main/java/com/serverless/Handler.java#L18). I added a log to `beforeHandleRequest`, as well as to each method in my [resource](https://github.com/ags799/learn-java/blob/as/dynamodb/src/main/java/com/serverless/GraphResource.java). None of these logs are showing up in `serverless logs -f all` (my function is named [`all`](https://github.com/ags799/learn-java/blob/as/dynamodb/serverless.yml#L25)).

Any idea why? Perhaps I should use a different command to obtain logs? Thanks.

**Comment by bbilger** [comment]
Hi @ags799 ,
I think you are missing a dependency to "org.slf4j:slf4j-log4j12:1.7.21"

**Comment by ags799** [comment]
Yep that did it! Thanks!
