### ISSUE TITLE
Can I use both SNS trigger and API Gateway in same application?

### ISSUE THREAD

**Issue by connect2code** [bbilger/jrestless#38]
Hi
I want to invoke some of the mvc apis through and some through sns invocation. Is there any way to do it in present framework ?

**Comment by bbilger** [comment]
Hi,
At the moment it is not possible to have one handler that handles both SNS and APIGW.
Though it shouldn't be too difficult to implement this.
However, the best you can do at the moment is to have 2 separate lambda functions (i.e. RequestHandlers) and let them share the same code (i.e. project/module that contains your business logic). Would this be a possible solution for you?

**Comment by connect2code** [comment]
Hi
Thanks for your quick reply.
Yes I thought of same workaround for quick implementation.

I will be having 2 APIs in a lambda function(Business Logic function) and have 2 other lambda functions(one invoked through API Gateway and other through SNS invocation) calling my Business Logic function.
