### ISSUE TITLE
Running locally

### ISSUE THREAD

**Issue by vinu** [bbilger/jrestless#47]
What is the best way to run the lambda service locally? say inside tomcat or some? So to rest the endpoints like localhost:8080/api 
thanks

**Comment by bbilger** [comment]
Hi @vinu ,

JRestless is a Jersey container i.e. you can run JAX-RS applications with it but only within a AWS lambda runtime environment.

What I would suggest - and that's actually the reason for this project - is to implement your "core" application including JAX-RS "Resources"/Controllers in a separate project (`App`).

On top of this you'll need two additional "technical" projects:
1. `Lambda` which has a dependency on `App` + `JRestless` 
2. `Local` which has a dependency on `App` + `Embedded Jetty` or deploy it to e.g. Tomcat EE.

You would then be able to deploy the `Lambda` project to AWS lambda and the `Local` project would be used to run/test your application locally.

```
             *-------------------*
      +----> | JRestless         |
      |      *-------------------*
      |
*-------------------*
| Lambda            |----+
*-------------------*    |
                         |      *-------------------*
                         +----> | App               |
                         |      *-------------------*
*-------------------*    |
| Local             |----+
*-------------------*
      |
      |      *-------------------*
      +----> | Embedded Jetty    |
             *-------------------*
```

Hope this helps.
